---
version: '2.2'
# Pinned at version 2.x to use resource limitation
networks:
  graphite_net:
    driver: bridge

services:
  graphite_web:
    build:
      context: graphite_web
    image: neofob/graphite_web:${GRAPHITE_WEB_TAG}
    hostname: graphite_web
    container_name: graphite_web
    volumes:
      - ${GRAPHITE_STORAGE}:/var/lib/graphite/storage
    restart: unless-stopped
    command:
      - "-b0.0.0.0:${GRAPHITE_WEB_PORT}"
      - "-w${GRAPHITE_WEB_W}"
      - "graphite.graphite_wsgi:application"
    networks:
      - graphite_net
    memswap_limit: -1
    mem_limit: ${GRAPHITE_WEB_MEM}

  webui:
    build:
      context: webui
    image: neofob/graphite_webui:${WEBUI_TAG}
    hostname: webui
    container_name: webui
    ports:
      - 80:80
    depends_on:
      - graphite_web
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=80
    depends_on:
      - graphite_web
    volumes:
      - ${CONFIG_DIR}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - graphite_net
    memswap_limit: -1
    mem_limit: ${WEBUI_MEM}

  relay:
    build:
      context: relay
      args:
        VERSION: ${RELAY_VERSION}
    image: neofob/relay:${RELAY_VERSION}
    hostname: relay
    container_name: relay
    ports:
      - 2003:2003
    volumes:
      - ${CONFIG_DIR}/etc/carbon-c-relay/carbon-c-relay.conf:/etc/carbon-c-relay/carbon-c-relay.conf:ro
    restart: unless-stopped
    depends_on:
      - go-carbon
    networks:
      - graphite_net
    command:
      - "-f"
      - "/etc/carbon-c-relay/carbon-c-relay.conf"
      - "-w"
      - "${RELAY_WORKER}"

  go-carbon:
    build: .
    image: neofob/go-carbon:${GO_TAG}
    hostname: go-carbon
#    ports:
#      - 2004:2004
#      - 7002:7002
    volumes:
      - ${GRAPHITE_STORAGE}:/var/lib/graphite/storage
      - ${LOG_DIR}:/var/log/supervisor
      - ${LOG_DIR}:/var/log/go-carbon
      - ${CONFIG_DIR}:/conf:ro
    restart: unless-stopped
    container_name: go-carbon
    networks:
      - graphite_net
    memswap_limit: -1
    mem_limit: ${GRAPHITE_MEM}

# __author__: tuan t. pham
